server:
  servlet:
    context-path: /api

endpoints:
  default:
    web:
      enabled: true

management:
  endpoint:
    info:
      enabled: true
    beans:
      enabled: true

spring:
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: "/var/lucene/indexes"
        temp:
          use_jdbc_metadata_defaults: false # Disable retrieving metadata from db (as postgres does not support this)

logging:
  level:
    org.hibernate.search: INFO

api-suggestions-refresh-rate-milliseconds : 2000
